### ISSUE TITLE
[Metabase][Reports] User is not able to open the downloaded .xlsx file 

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/openchs-reporting#18]
https://avni.freshdesk.com/a/tickets/763

Error -
 ![Screen Shot 2020-09-16 at 11.46.46 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/40162dfa-4a71-4394-ad17-f3f1d8b5b8b2)

**Comment by 1t5j0y** [comment]
Raised issue with Metabase
https://github.com/metabase/metabase/issues/13282

**Comment by 1t5j0y** [comment]
Resolved file system usage issue and restarted Metabase.
