### ISSUE TITLE
[Jasper Reports] Move LL for directly used by client in a separate folder.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/openchs-reporting#19]
https://docs.google.com/spreadsheets/d/162niLHjrvaCrSeU1NwwgAknK6fYC3IAx79_mmcjuZ9M/edit#gid=381423043

**Comment by 1t5j0y** [comment]
- [x] Verify that listed reports are not linked to from any aggregates
- [x] Create 'Independent Linelists' folder under Reports folder for yenepoya and JSSCP
- [x] Cut and Paste listed reports
