### ISSUE TITLE
Optimize long running report queries causing CPU spike

### ISSUE THREAD

**Issue by 1t5j0y** [OpenCHS/openchs-reporting#21]
Optimise few JSS queries that are taking long time to execute which are spiking the CPU on the read database.

1. https://avni.freshdesk.com/a/tickets/798
DB user: jss
[Log file](https://app.zenhub.com/files/118568718/c68fa7d7-36fb-4ba1-af5e-4f4a0088b09e/download) - Search for text: "duration" (value over 50000ms)
Reports using these queries: https://reporting.avniproject.org/question/143

2. https://avni.freshdesk.com/a/tickets/802
DB user: jsscp
[Log file](https://app.zenhub.com/files/118568718/284afe3e-17f4-4a12-b7e1-6c67d11d231f/download) - Timestamp:11:40:16
Reports using this query: https://reporting.avniproject.org/question/520 https://reporting.avniproject.org/question/476 https://reporting.avniproject.org/question/940, Jasper JSSCP Aggregate - Antenatal services during pregnancy.

3. https://avni.freshdesk.com/a/tickets/804
DB user: jsscp (Query structure is similar to case 1 above)
[Log file](https://app.zenhub.com/files/118568718/2b2883af-1779-4a1d-90a8-fa246a02715f/download) - Timestamp:04:49:36
Reports using this query: https://reporting.avniproject.org/question/940 https://reporting.avniproject.org/question/683

Steps to optimize:
Refer to [this doc](https://docs.google.com/document/d/1QPvPoa7XC3xGcx1l_P8gLvVkfZ9fduRyBUvg1iL-uys/edit)

**Comment by arjunk** [comment]
how does someone QA these cards?

**Comment by 1t5j0y** [comment]
1. Compare with previous version to ensure output is the same
2. Ensure that no CPU spike ticket is created when report is executed

**Comment by 1t5j0y** [comment]
Closed tickets 798, 802 and 804
